"""
What errors are generated by the following code snippets?
"""

#---
number_dictionary = {
                     "Adam": "928-792-2845",
                     "Selena": "928-792-2846",
                     "Morty": "928-792-2847"
                     }

#print(number_dictionary["Rodney"])
#---


number_string = "17"

# Make Adam an integer
my_name = "Adam"
#number = int(my_name)

#---


#print(my_age)

#---


my_list = ["Hello", True, "Goodbye", False]


#print(my_list[4])


#---


name = "Adrian"
age = 23

#print(name + age)

#---